### ISSUE TITLE
Questionable library: invisible-watermark

### ISSUE THREAD

**Issue by Derjyn** [hako-mikan/sd-webui-traintrain#13]
Why is this library in there? As soon as seeing this included, my assumption is that you are placing your own watermarks on generated content. I hope I'm wrong, but some clarification would be great!

I'll be diving into the source code in the meantime, to see if I can figure out why this library is included and how it is being utilized...

**Comment by Derjyn** [comment]
Update: After diving into the scripts, I'm not seeing any reference to watermarks of any sort. So it seems that library referenced in the install script is unnecessary? I removed the references and library packages, and haven't seen any issues yet.

Might be a little fix/change to make in a future update :)

**Comment by hako-mikan** [comment]
It seems unnecessary, as you said. It looks like I forgot to remove something that became unnecessary, which was used during the development stage.
It was deleted.
Thank you.
