### ISSUE TITLE
Extension fails to load

### ISSUE THREAD

**Issue by Lumabrik** [hako-mikan/sd-webui-traintrain#2]
after installing and rebooting there is this error .......

*** Error executing callback app_started_callback for C:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-traintrain\scripts\traintrain.py
    Traceback (most recent call last):
      File "C:\StableDiffusion\stable-diffusion-webui\modules\script_callbacks.py", line 142, in app_started_callback
        c.callback(demo, app)
      File "C:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-traintrain\scripts\traintrain.py", line 497, in get_params_components
        inputs=[gr.Checkbox(value=False, visible=False), prompts[0], prompts[2], *txt2img_params],
    TypeError: 'NoneType' object is not subscriptable

**Comment by strawberrymelonpanda** [comment]
Same, using the latest Dev build of WebUI.

**Comment by strawberrymelonpanda** [comment]
Just double-checked: it works for me on the latest master build, but not on Dev.

**Comment by Lumabrik** [comment]
Yes, that was my issue ... just realised I was also on the dev branch

**Comment by strawberrymelonpanda** [comment]
👍 Still worth keeping the issue open in my opinion, as the dev build contains a *lot* of improvements.

**Comment by hako-mikan** [comment]
maybe fixed
