### ISSUE TITLE
学習に使われたタグの確認

### ISSUE THREAD

**Issue by nanumin** [hako-mikan/sd-webui-traintrain#5]
学習に使われたタグをwebUI側から確認できません。
save as jsonで疑似的に記録、確認などはできないでしょうか？

**Comment by hako-mikan** [comment]
保存するようになりました。内容はweb-uiで確認できます。

**Comment by nanumin** [comment]
ありがとうございます！

**Comment by nanumin** [comment]
すみません。web-uiでタグの確認できません。
・web-UIのバージョンは1.7.0
・network typeはlierla
・学習に使用したモデルは Animagine xl 3.0
タグはtaggerを使用した.txtファイルにTrainTrain側からトリガーワードを追加しています。
<img width="321" alt="traintrain" src="https://github.com/hako-mikan/sd-webui-traintrain/assets/158801941/d03794b0-7aef-45af-ba4e-52e22ced11d3">
