### ISSUE TITLE
学習に使われたタグの確認#再

### ISSUE THREAD

**Issue by nanumin** [hako-mikan/sd-webui-traintrain#8]
すみません。最新版に更新しましたがweb-ui側でタグの確認できません。
・web-UIのバージョンは1.7.0
・network typeはlierla
・学習に使用したモデルは Animagine xl 3.0
タグはtaggerを使用して用意した.txtファイルにTrainTrain側からトリガーワードを追加しています。
<img width="321" alt="traintrain" src="https://github.com/hako-mikan/sd-webui-traintrain/assets/158801941/789b9db4-9ddf-4333-ad01-9a57c14f4e3c">

**Comment by nanumin** [comment]
追記
.txtのみで学習してみましたが結果は同じくTraining dataset tagsが空欄のままでした。

**Comment by hako-mikan** [comment]
こちらではちゃんと動いているので不思議ですね。
一度拡張の再インストールを試してもらえますでしょうか。
最新かどうかの確認としては、dataset.pyの293行目が`t.tagcount(prompt)`となっていれば最新のはずですが。

**Comment by nanumin** [comment]
私のほうで更新がうまくいっていなかったようです。
再度入れなおしたらTraining dataset tags見れるようになりました。
お騒がせしてすみません。
