### ISSUE TITLE
Difference学習の際のimage_sizeについて

### ISSUE THREAD

**Issue by nanumin** [hako-mikan/sd-webui-traintrain#9]
Difference学習の設定項目の中にimage_sizeはありませんが、保存されたjsonを確認するとimage_size(height, width):"512"となっています。
用意した画像のサイズに関わらずDifferenceの学習時の解像度は一定で1024や768に変えることはできない、あるいは変える必要性が無いのでしょうか？

**Comment by hako-mikan** [comment]
変える必要はありません。Differenceの場合にはサイズは自動的に画像から取得されます。
